# This is a basic workflow to help you get started with Actions

name: Update rssbot version

# Controls when the action will run.
on:
  workflow_dispatch:
  
  schedule:
    - cron: 0 16 * * *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-tomcat:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_PAT }}
      
      - name: Setup git and gpg keys
        run: |
          echo "${{ secrets.BOT_PGP_KEY }}" | gpg --import --batch --always-trust
          echo "${{ secrets.BOT_PGP_FINGER }}:6:" | gpg --import-ownertrust
          echo | gpg --clearsign --pinentry-mode loopback --passphrase '${{ secrets.BOT_PGP_PASS }}' > /dev/null
          git config user.name superjeng1-bot
          git config user.email 71003564+superjeng1-bot@users.noreply.github.com
          git config user.signingkey ${{ secrets.BOT_PGP_KEY_ID }}
      
      - name: Check Latest docker.io/alpine:latest sha256 checksum
        run: |
          rssbotVersion=curl -sL https://api.github.com/repos/iovxw/rssbot/releases/latest | jq -r ".tag_name"
          perl -i -pe 's/^(ENV) RSSBOT_VERSION.+/\1 RSSBOT_VERSION '"$rssbotVersion"'/gm' Dockerfile
          git add -u
          git diff-index --quiet HEAD && echo "No update available for now. Exiting..." || { git commit -S -m "Updated rssbot version to $rssbotVersion"; }

      - name: Git Push to remote
        run: git push
